/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedCustosRouteImport } from './routes/_authenticated/custos'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedEstafetasRouteImport } from './routes/_authenticated/estafetas'
import { Route as AuthenticatedRelatoriosRouteImport } from './routes/_authenticated/relatorios'
import { Route as AuthenticatedStudioRouteImport } from './routes/_authenticated/studio'
import { Route as AuthenticatedVeiculosRouteImport } from './routes/_authenticated/veiculos'
import { Route as AuthenticatedAppIndexRouteImport } from './routes/_authenticated/app.index'
import { Route as AuthenticatedAppPontoRouteImport } from './routes/_authenticated/app.ponto'
import { Route as AuthenticatedAppResumoRouteImport } from './routes/_authenticated/app.resumo'
import { Route as AuthenticatedRotasIndexRouteImport } from './routes/_authenticated/rotas.index'
import { Route as AuthenticatedRotasIdRouteImport } from './routes/_authenticated/rotas.$id'
import { Route as AuthenticatedStudioIndexRouteImport } from './routes/_authenticated/studio.index'
import { Route as AuthenticatedStudioApiRouteImport } from './routes/_authenticated/studio.api'
import { Route as AuthenticatedStudioDocsRouteImport } from './routes/_authenticated/studio.docs'
import { Route as AuthenticatedStudioMcpRouteImport } from './routes/_authenticated/studio.mcp'
import { Route as AuthenticatedStudioWebhooksRouteImport } from './routes/_authenticated/studio.webhooks'
import { Route as ApiPublicMcpRouteImport } from './routes/api/public/mcp'
import { Route as ApiPublicOpenapiDotjsonRouteImport } from './routes/api/public/openapi[.]json'
import { Route as AuthenticatedAppParadaIdRouteImport } from './routes/_authenticated/app.parada.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedCustosRoute = AuthenticatedCustosRouteImport.update({
  id: '/custos',
  path: '/custos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEstafetasRoute = AuthenticatedEstafetasRouteImport.update({
  id: '/estafetas',
  path: '/estafetas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRelatoriosRoute = AuthenticatedRelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedStudioRoute = AuthenticatedStudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedVeiculosRoute = AuthenticatedVeiculosRouteImport.update({
  id: '/veiculos',
  path: '/veiculos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppIndexRoute = AuthenticatedAppIndexRouteImport.update({
  id: '/app/',
  path: '/app/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppPontoRoute = AuthenticatedAppPontoRouteImport.update({
  id: '/app/ponto',
  path: '/app/ponto',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppResumoRoute = AuthenticatedAppResumoRouteImport.update({
  id: '/app/resumo',
  path: '/app/resumo',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRotasIndexRoute = AuthenticatedRotasIndexRouteImport.update({
  id: '/rotas/',
  path: '/rotas/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRotasIdRoute = AuthenticatedRotasIdRouteImport.update({
  id: '/rotas/$id',
  path: '/rotas/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedStudioIndexRoute =
  AuthenticatedStudioIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedStudioRoute,
  } as any)
const AuthenticatedStudioApiRoute = AuthenticatedStudioApiRouteImport.update({
  id: '/api',
  path: '/api',
  getParentRoute: () => AuthenticatedStudioRoute,
} as any)
const AuthenticatedStudioDocsRoute = AuthenticatedStudioDocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => AuthenticatedStudioRoute,
} as any)
const AuthenticatedStudioMcpRoute = AuthenticatedStudioMcpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => AuthenticatedStudioRoute,
} as any)
const AuthenticatedStudioWebhooksRoute =
  AuthenticatedStudioWebhooksRouteImport.update({
    id: '/webhooks',
    path: '/webhooks',
    getParentRoute: () => AuthenticatedStudioRoute,
  } as any)
const ApiPublicMcpRoute = ApiPublicMcpRouteImport.update({
  id: '/api/public/mcp',
  path: '/api/public/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicOpenapiDotjsonRoute = ApiPublicOpenapiDotjsonRouteImport.update({
  id: '/api/public/openapi.json',
  path: '/api/public/openapi.json',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppParadaIdRoute =
  AuthenticatedAppParadaIdRouteImport.update({
    id: '/app/parada/$id',
    path: '/app/parada/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/custos': typeof AuthenticatedCustosRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/estafetas': typeof AuthenticatedEstafetasRoute
  '/relatorios': typeof AuthenticatedRelatoriosRoute
  '/studio': typeof AuthenticatedStudioRouteWithChildren
  '/veiculos': typeof AuthenticatedVeiculosRoute
  '/app/ponto': typeof AuthenticatedAppPontoRoute
  '/app/resumo': typeof AuthenticatedAppResumoRoute
  '/rotas/$id': typeof AuthenticatedRotasIdRoute
  '/studio/api': typeof AuthenticatedStudioApiRoute
  '/studio/docs': typeof AuthenticatedStudioDocsRoute
  '/studio/mcp': typeof AuthenticatedStudioMcpRoute
  '/studio/webhooks': typeof AuthenticatedStudioWebhooksRoute
  '/api/public/mcp': typeof ApiPublicMcpRoute
  '/api/public/openapi.json': typeof ApiPublicOpenapiDotjsonRoute
  '/app/': typeof AuthenticatedAppIndexRoute
  '/rotas/': typeof AuthenticatedRotasIndexRoute
  '/studio/': typeof AuthenticatedStudioIndexRoute
  '/app/parada/$id': typeof AuthenticatedAppParadaIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/custos': typeof AuthenticatedCustosRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/estafetas': typeof AuthenticatedEstafetasRoute
  '/relatorios': typeof AuthenticatedRelatoriosRoute
  '/veiculos': typeof AuthenticatedVeiculosRoute
  '/app/ponto': typeof AuthenticatedAppPontoRoute
  '/app/resumo': typeof AuthenticatedAppResumoRoute
  '/rotas/$id': typeof AuthenticatedRotasIdRoute
  '/studio/api': typeof AuthenticatedStudioApiRoute
  '/studio/docs': typeof AuthenticatedStudioDocsRoute
  '/studio/mcp': typeof AuthenticatedStudioMcpRoute
  '/studio/webhooks': typeof AuthenticatedStudioWebhooksRoute
  '/api/public/mcp': typeof ApiPublicMcpRoute
  '/api/public/openapi.json': typeof ApiPublicOpenapiDotjsonRoute
  '/app': typeof AuthenticatedAppIndexRoute
  '/rotas': typeof AuthenticatedRotasIndexRoute
  '/studio': typeof AuthenticatedStudioIndexRoute
  '/app/parada/$id': typeof AuthenticatedAppParadaIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/custos': typeof AuthenticatedCustosRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/estafetas': typeof AuthenticatedEstafetasRoute
  '/_authenticated/relatorios': typeof AuthenticatedRelatoriosRoute
  '/_authenticated/studio': typeof AuthenticatedStudioRouteWithChildren
  '/_authenticated/veiculos': typeof AuthenticatedVeiculosRoute
  '/_authenticated/app/ponto': typeof AuthenticatedAppPontoRoute
  '/_authenticated/app/resumo': typeof AuthenticatedAppResumoRoute
  '/_authenticated/rotas/$id': typeof AuthenticatedRotasIdRoute
  '/_authenticated/studio/api': typeof AuthenticatedStudioApiRoute
  '/_authenticated/studio/docs': typeof AuthenticatedStudioDocsRoute
  '/_authenticated/studio/mcp': typeof AuthenticatedStudioMcpRoute
  '/_authenticated/studio/webhooks': typeof AuthenticatedStudioWebhooksRoute
  '/api/public/mcp': typeof ApiPublicMcpRoute
  '/api/public/openapi.json': typeof ApiPublicOpenapiDotjsonRoute
  '/_authenticated/app/': typeof AuthenticatedAppIndexRoute
  '/_authenticated/rotas/': typeof AuthenticatedRotasIndexRoute
  '/_authenticated/studio/': typeof AuthenticatedStudioIndexRoute
  '/_authenticated/app/parada/$id': typeof AuthenticatedAppParadaIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/custos'
    | '/dashboard'
    | '/estafetas'
    | '/relatorios'
    | '/studio'
    | '/veiculos'
    | '/app/ponto'
    | '/app/resumo'
    | '/rotas/$id'
    | '/studio/api'
    | '/studio/docs'
    | '/studio/mcp'
    | '/studio/webhooks'
    | '/api/public/mcp'
    | '/api/public/openapi.json'
    | '/app/'
    | '/rotas/'
    | '/studio/'
    | '/app/parada/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/custos'
    | '/dashboard'
    | '/estafetas'
    | '/relatorios'
    | '/veiculos'
    | '/app/ponto'
    | '/app/resumo'
    | '/rotas/$id'
    | '/studio/api'
    | '/studio/docs'
    | '/studio/mcp'
    | '/studio/webhooks'
    | '/api/public/mcp'
    | '/api/public/openapi.json'
    | '/app'
    | '/rotas'
    | '/studio'
    | '/app/parada/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/custos'
    | '/_authenticated/dashboard'
    | '/_authenticated/estafetas'
    | '/_authenticated/relatorios'
    | '/_authenticated/studio'
    | '/_authenticated/veiculos'
    | '/_authenticated/app/ponto'
    | '/_authenticated/app/resumo'
    | '/_authenticated/rotas/$id'
    | '/_authenticated/studio/api'
    | '/_authenticated/studio/docs'
    | '/_authenticated/studio/mcp'
    | '/_authenticated/studio/webhooks'
    | '/api/public/mcp'
    | '/api/public/openapi.json'
    | '/_authenticated/app/'
    | '/_authenticated/rotas/'
    | '/_authenticated/studio/'
    | '/_authenticated/app/parada/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiPublicMcpRoute: typeof ApiPublicMcpRoute
  ApiPublicOpenapiDotjsonRoute: typeof ApiPublicOpenapiDotjsonRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/custos': {
      id: '/_authenticated/custos'
      path: '/custos'
      fullPath: '/custos'
      preLoaderRoute: typeof AuthenticatedCustosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/estafetas': {
      id: '/_authenticated/estafetas'
      path: '/estafetas'
      fullPath: '/estafetas'
      preLoaderRoute: typeof AuthenticatedEstafetasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/relatorios': {
      id: '/_authenticated/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof AuthenticatedRelatoriosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/studio': {
      id: '/_authenticated/studio'
      path: '/studio'
      fullPath: '/studio'
      preLoaderRoute: typeof AuthenticatedStudioRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/veiculos': {
      id: '/_authenticated/veiculos'
      path: '/veiculos'
      fullPath: '/veiculos'
      preLoaderRoute: typeof AuthenticatedVeiculosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/': {
      id: '/_authenticated/app/'
      path: '/app'
      fullPath: '/app/'
      preLoaderRoute: typeof AuthenticatedAppIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/ponto': {
      id: '/_authenticated/app/ponto'
      path: '/app/ponto'
      fullPath: '/app/ponto'
      preLoaderRoute: typeof AuthenticatedAppPontoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/resumo': {
      id: '/_authenticated/app/resumo'
      path: '/app/resumo'
      fullPath: '/app/resumo'
      preLoaderRoute: typeof AuthenticatedAppResumoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/rotas/': {
      id: '/_authenticated/rotas/'
      path: '/rotas'
      fullPath: '/rotas/'
      preLoaderRoute: typeof AuthenticatedRotasIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/rotas/$id': {
      id: '/_authenticated/rotas/$id'
      path: '/rotas/$id'
      fullPath: '/rotas/$id'
      preLoaderRoute: typeof AuthenticatedRotasIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/studio/': {
      id: '/_authenticated/studio/'
      path: '/'
      fullPath: '/studio/'
      preLoaderRoute: typeof AuthenticatedStudioIndexRouteImport
      parentRoute: typeof AuthenticatedStudioRoute
    }
    '/_authenticated/studio/api': {
      id: '/_authenticated/studio/api'
      path: '/api'
      fullPath: '/studio/api'
      preLoaderRoute: typeof AuthenticatedStudioApiRouteImport
      parentRoute: typeof AuthenticatedStudioRoute
    }
    '/_authenticated/studio/docs': {
      id: '/_authenticated/studio/docs'
      path: '/docs'
      fullPath: '/studio/docs'
      preLoaderRoute: typeof AuthenticatedStudioDocsRouteImport
      parentRoute: typeof AuthenticatedStudioRoute
    }
    '/_authenticated/studio/mcp': {
      id: '/_authenticated/studio/mcp'
      path: '/mcp'
      fullPath: '/studio/mcp'
      preLoaderRoute: typeof AuthenticatedStudioMcpRouteImport
      parentRoute: typeof AuthenticatedStudioRoute
    }
    '/_authenticated/studio/webhooks': {
      id: '/_authenticated/studio/webhooks'
      path: '/webhooks'
      fullPath: '/studio/webhooks'
      preLoaderRoute: typeof AuthenticatedStudioWebhooksRouteImport
      parentRoute: typeof AuthenticatedStudioRoute
    }
    '/api/public/mcp': {
      id: '/api/public/mcp'
      path: '/api/public/mcp'
      fullPath: '/api/public/mcp'
      preLoaderRoute: typeof ApiPublicMcpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/openapi.json': {
      id: '/api/public/openapi.json'
      path: '/api/public/openapi.json'
      fullPath: '/api/public/openapi.json'
      preLoaderRoute: typeof ApiPublicOpenapiDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app/parada/$id': {
      id: '/_authenticated/app/parada/$id'
      path: '/app/parada/$id'
      fullPath: '/app/parada/$id'
      preLoaderRoute: typeof AuthenticatedAppParadaIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedStudioRouteChildren {
  AuthenticatedStudioApiRoute: typeof AuthenticatedStudioApiRoute
  AuthenticatedStudioDocsRoute: typeof AuthenticatedStudioDocsRoute
  AuthenticatedStudioMcpRoute: typeof AuthenticatedStudioMcpRoute
  AuthenticatedStudioWebhooksRoute: typeof AuthenticatedStudioWebhooksRoute
  AuthenticatedStudioIndexRoute: typeof AuthenticatedStudioIndexRoute
}

const AuthenticatedStudioRouteChildren: AuthenticatedStudioRouteChildren = {
  AuthenticatedStudioApiRoute: AuthenticatedStudioApiRoute,
  AuthenticatedStudioDocsRoute: AuthenticatedStudioDocsRoute,
  AuthenticatedStudioMcpRoute: AuthenticatedStudioMcpRoute,
  AuthenticatedStudioWebhooksRoute: AuthenticatedStudioWebhooksRoute,
  AuthenticatedStudioIndexRoute: AuthenticatedStudioIndexRoute,
}

const AuthenticatedStudioRouteWithChildren =
  AuthenticatedStudioRoute._addFileChildren(AuthenticatedStudioRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedCustosRoute: typeof AuthenticatedCustosRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedEstafetasRoute: typeof AuthenticatedEstafetasRoute
  AuthenticatedRelatoriosRoute: typeof AuthenticatedRelatoriosRoute
  AuthenticatedStudioRoute: typeof AuthenticatedStudioRouteWithChildren
  AuthenticatedVeiculosRoute: typeof AuthenticatedVeiculosRoute
  AuthenticatedAppPontoRoute: typeof AuthenticatedAppPontoRoute
  AuthenticatedAppResumoRoute: typeof AuthenticatedAppResumoRoute
  AuthenticatedRotasIdRoute: typeof AuthenticatedRotasIdRoute
  AuthenticatedAppIndexRoute: typeof AuthenticatedAppIndexRoute
  AuthenticatedRotasIndexRoute: typeof AuthenticatedRotasIndexRoute
  AuthenticatedAppParadaIdRoute: typeof AuthenticatedAppParadaIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedCustosRoute: AuthenticatedCustosRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedEstafetasRoute: AuthenticatedEstafetasRoute,
  AuthenticatedRelatoriosRoute: AuthenticatedRelatoriosRoute,
  AuthenticatedStudioRoute: AuthenticatedStudioRouteWithChildren,
  AuthenticatedVeiculosRoute: AuthenticatedVeiculosRoute,
  AuthenticatedAppPontoRoute: AuthenticatedAppPontoRoute,
  AuthenticatedAppResumoRoute: AuthenticatedAppResumoRoute,
  AuthenticatedRotasIdRoute: AuthenticatedRotasIdRoute,
  AuthenticatedAppIndexRoute: AuthenticatedAppIndexRoute,
  AuthenticatedRotasIndexRoute: AuthenticatedRotasIndexRoute,
  AuthenticatedAppParadaIdRoute: AuthenticatedAppParadaIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiPublicMcpRoute: ApiPublicMcpRoute,
  ApiPublicOpenapiDotjsonRoute: ApiPublicOpenapiDotjsonRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
